config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  root :to => "projects#index"

  resources :files

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  namespace :admin do
    root :to => "base#index"
    resources :users do
      resources :permissions
    end
    resources :states
  end

  get '/awaiting_confirmation', :to => "users#confirmation", :as => 'confirm_user'

  put '/admin/users/:user_id/permissions',
     :to => 'admin/permissions#update',
     :as => :update_user_permissions

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :background, :color, :name

  belongs_to :state

  def to_s 
    name
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController

  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(params[:state])
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created."
      render :action => "new"
    end
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
 <p>
   <%= f.label :name %>
   <%= f.text_field :name %>
 </p>
 <%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", new_admin_state_path %>
<ul id='states'>
  <% for state in @states %>
    <li><%= state.name %></li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h1>New State</h1>
<%= render "form" %>